server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: ordenes-route
          uri: lb://ordenes-service
          predicates:
            - Path=/ordenes/**
        - id: envios-route
          uri: lb://ordenes-service
          predicates:
            - Path=/envios/**
        - id: pagos-route
          uri: lb://pagos-service
          predicates:
            - Path=/pagos/**

        - id: productos-route
          uri: lb://product-service
          predicates:
              - Path=/productos/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true